<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#pandas-시작하기" data-toc-modified-id="pandas-시작하기-1">pandas 시작하기</a></span><ul class="toc-item"><li><span><a href="#5.1-pandas-자료구조-소개" data-toc-modified-id="5.1-pandas-자료구조-소개-1.1">5.1 pandas 자료구조 소개</a></span><ul class="toc-item"><li><span><a href="#5.1.1-Series" data-toc-modified-id="5.1.1-Series-1.1.1">5.1.1 Series</a></span></li><li><span><a href="#5.1.2-DataFrame" data-toc-modified-id="5.1.2-DataFrame-1.1.2">5.1.2 DataFrame</a></span></li><li><span><a href="#5.1.3-색인-객체" data-toc-modified-id="5.1.3-색인-객체-1.1.3">5.1.3 색인 객체</a></span></li></ul></li></ul></li></ul></div>

# pandas 시작하기

In [1]:
import pandas as pd
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## 5.1 pandas 자료구조 소개
### 5.1.1 Series

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index  # range(4)와 동일

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])  # 인덱스 지정
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
obj2['d'] = 6

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)  # 딕셔너리로 시리즈 생성
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)  # 인덱스 순서 지정
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
obj4.name = 'population'   # 시리즈 객체의 name
obj4.index.name = 'state'  # 인덱스의 name
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']  # 인덱스 변경
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [2]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [3]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [4]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [5]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])  # 컬럼 순서 지정

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [6]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2  # 딕셔너리에 없는 값은 결측치로 채워짐

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [7]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [8]:
frame2['state']  # 딕셔너리 형식으로 컬럼 접근

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [9]:
frame2.year  # 속성 형식으로 컬럼 접근

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [10]:
frame2.loc['three']  # loc 형식으로 로우 접근

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [11]:
frame2['debt'] = 16.5  # 컬럼에 스칼라 값 대입
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [12]:
frame2['debt'] = np.arange(6.)  # 컬럼에 배열 대입
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [13]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val  # 컬럼에 시리즈를 대입하면 인덱스에 따라 값이 대입됨
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [17]:
frame2['eastern'] = frame2.state == 'Ohio'  # 새로운 컬럼 생성
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [18]:
del frame2['eastern']  # 컬럼 삭제
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [19]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},           # 중첩된 딕셔너리로 데이터프레임 생성
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}  # 바깥쪽 키는 컬럼, 안쪽 키는 로우가 됨
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [20]:
frame3.T  # 데이터프레임 전치

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [21]:
pd.DataFrame(pop, index=[2001, 2002, 2003])  # 인덱스 직접 지정

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [27]:
pdata = {'Ohio': frame3['Ohio'][:-1],     # 시리즈를 담고 있는 딕셔너리로
         'Nevada': frame3['Nevada'][:2]}  # 데이터프레임 생성
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [30]:
frame3.index.name = 'year'  # name 속성 지정
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [31]:
frame3.values  # 데이터를 2차원 배열로 반환

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [32]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 색인 객체

In [34]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [35]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [36]:
index[1:]

Index(['b', 'c'], dtype='object')

In [37]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [38]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [39]:
obj2.index is labels

True

In [40]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [41]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [42]:
'Ohio' in frame3.columns

True

In [43]:
2003 in frame3.index

False

In [44]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')