<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#pandas-시작하기" data-toc-modified-id="pandas-시작하기-1">pandas 시작하기</a></span><ul class="toc-item"><li><span><a href="#5.1-pandas-자료구조-소개" data-toc-modified-id="5.1-pandas-자료구조-소개-1.1">5.1 pandas 자료구조 소개</a></span><ul class="toc-item"><li><span><a href="#5.1.1-Series" data-toc-modified-id="5.1.1-Series-1.1.1">5.1.1 Series</a></span></li><li><span><a href="#5.1.2-DataFrame" data-toc-modified-id="5.1.2-DataFrame-1.1.2">5.1.2 DataFrame</a></span></li><li><span><a href="#5.1.3-인덱스-객체" data-toc-modified-id="5.1.3-인덱스-객체-1.1.3">5.1.3 인덱스 객체</a></span></li></ul></li><li><span><a href="#5.2-핵심-기능" data-toc-modified-id="5.2-핵심-기능-1.2">5.2 핵심 기능</a></span><ul class="toc-item"><li><span><a href="#5.2.1-리인덱싱" data-toc-modified-id="5.2.1-리인덱싱-1.2.1">5.2.1 리인덱싱</a></span></li><li><span><a href="#5.2.2-하나의-로우나-컬럼-삭제하기" data-toc-modified-id="5.2.2-하나의-로우나-컬럼-삭제하기-1.2.2">5.2.2 하나의 로우나 컬럼 삭제하기</a></span></li><li><span><a href="#5.2.3-인덱싱,-선택하기,-필터링" data-toc-modified-id="5.2.3-인덱싱,-선택하기,-필터링-1.2.3">5.2.3 인덱싱, 선택하기, 필터링</a></span><ul class="toc-item"><li><span><a href="#loc와-iloc으로-선택하기" data-toc-modified-id="loc와-iloc으로-선택하기-1.2.3.1">loc와 iloc으로 선택하기</a></span></li></ul></li><li><span><a href="#5.2.4-정수-인덱스" data-toc-modified-id="5.2.4-정수-인덱스-1.2.4">5.2.4 정수 인덱스</a></span></li><li><span><a href="#5.2.5-산술-연산과-데이터-정렬" data-toc-modified-id="5.2.5-산술-연산과-데이터-정렬-1.2.5">5.2.5 산술 연산과 데이터 정렬</a></span><ul class="toc-item"><li><span><a href="#산술-연산-메서드에-채워-넣을-값-지정하기" data-toc-modified-id="산술-연산-메서드에-채워-넣을-값-지정하기-1.2.5.1">산술 연산 메서드에 채워 넣을 값 지정하기</a></span></li><li><span><a href="#DataFrame과-Series-간의-연산" data-toc-modified-id="DataFrame과-Series-간의-연산-1.2.5.2">DataFrame과 Series 간의 연산</a></span></li></ul></li><li><span><a href="#5.2.6-함수-적용과-매핑" data-toc-modified-id="5.2.6-함수-적용과-매핑-1.2.6">5.2.6 함수 적용과 매핑</a></span></li><li><span><a href="#5.2.7-정렬과-순위" data-toc-modified-id="5.2.7-정렬과-순위-1.2.7">5.2.7 정렬과 순위</a></span></li><li><span><a href="#5.2.8-중복-인덱스" data-toc-modified-id="5.2.8-중복-인덱스-1.2.8">5.2.8 중복 인덱스</a></span></li></ul></li><li><span><a href="#5.3-기술-통계-계산과-요약" data-toc-modified-id="5.3-기술-통계-계산과-요약-1.3">5.3 기술 통계 계산과 요약</a></span><ul class="toc-item"><li><span><a href="#5.3.1-상관관계와-공분산" data-toc-modified-id="5.3.1-상관관계와-공분산-1.3.1">5.3.1 상관관계와 공분산</a></span></li><li><span><a href="#5.3.2-유일값,-값-세기,-멤버십" data-toc-modified-id="5.3.2-유일값,-값-세기,-멤버십-1.3.2">5.3.2 유일값, 값 세기, 멤버십</a></span></li></ul></li></ul></li></ul></div>

# pandas 시작하기

In [1]:
import pandas as pd
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## 5.1 pandas 자료구조 소개
### 5.1.1 Series

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index  # range(4)와 동일

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])  # 인덱스 지정
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
obj2['d'] = 6

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)  # 딕셔너리로 시리즈 생성
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)  # 인덱스 순서 지정
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
obj4.name = 'population'   # 시리즈 객체의 name
obj4.index.name = 'state'  # 인덱스의 name
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [22]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']  # 인덱스 변경
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [23]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [24]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [26]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])  # 컬럼 순서 지정

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [27]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2  # 딕셔너리에 없는 값은 결측치로 채워짐

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2['state']  # 딕셔너리 형식으로 컬럼 접근

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [30]:
frame2.year  # 속성 형식으로 컬럼 접근

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [31]:
frame2.loc['three']  # loc 형식으로 로우 접근

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [32]:
frame2['debt'] = 16.5  # 컬럼에 스칼라 값 대입
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [33]:
frame2['debt'] = np.arange(6.)  # 컬럼에 배열 대입
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [34]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val  # 컬럼에 시리즈를 대입하면 인덱스에 따라 값이 대입됨
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [35]:
frame2['eastern'] = frame2.state == 'Ohio'  # 새로운 컬럼 생성
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [36]:
del frame2['eastern']  # 컬럼 삭제
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},           # 중첩된 딕셔너리로 데이터프레임 생성
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}  # 바깥쪽 키는 컬럼, 안쪽 키는 로우가 됨
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [38]:
frame3.T  # 데이터프레임 전치

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [39]:
pd.DataFrame(pop, index=[2001, 2002, 2003])  # 인덱스 직접 지정

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [40]:
pdata = {'Ohio': frame3['Ohio'][:-1],     # 시리즈를 담고 있는 딕셔너리로
         'Nevada': frame3['Nevada'][:2]}  # 데이터프레임 생성
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [41]:
frame3.index.name = 'year'  # name 속성 지정
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [42]:
frame3.values  # 데이터를 2차원 배열로 반환

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [43]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 인덱스 객체

In [44]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [45]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

In [47]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [48]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [49]:
obj2.index is labels

True

In [50]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [51]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [52]:
'Ohio' in frame3.columns

True

In [53]:
2003 in frame3.index

False

In [54]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])  # pandas 인덱스는 중복값 허용
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 핵심 기능
### 5.2.1 리인덱싱

In [55]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [56]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])  # 새로운 인덱스에 맞게 데이터 재배열
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [57]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [58]:
obj3.reindex(range(6), method='ffill')  # 누락된 값을 직전 값으로 채우는 method
# ffill: 직전 값, bfill: 다음 값으로 채우기

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [59]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [60]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])  # row reindexing
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [61]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)  # column reindexing

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [62]:
frame.loc[['a', 'c', 'd'], ['Texas', 'California']]  # loc로 명시적 인덱싱

Texas  California
a      1           2
c      4           5
d      7           8

### 5.2.2 하나의 로우나 컬럼 삭제하기

In [63]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [64]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [66]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [67]:
data.drop(['Colorado', 'Ohio'])  # 로우 삭제

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [68]:
data.drop('two', axis=1)  # 컬럼 삭제

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [69]:
data.drop(['two', 'four'], axis='columns')  # 컬럼 삭제

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [70]:
obj.drop('c', inplace=True)  # 원본 객체 변경
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 인덱싱, 선택하기, 필터링

In [71]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [72]:
obj['b']

1.0

In [73]:
obj[1]

1.0

In [74]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [75]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [76]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [77]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [78]:
obj['b':'c']  # 라벨 이름으로 슬리이싱하면 시작점과 끝점 포함

b    1.0
c    2.0
dtype: float64

In [79]:
obj['b':'c'] = 5  # 슬라이싱으로 선택된 영역에 값 대입
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [80]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
data['two']  # 컬럼 선택

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [82]:
data[['three', 'one']]  # 컬럼 선택

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [83]:
data[:2]  # 로우 선택

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [84]:
data[data['three'] > 5]  # 로우 선택

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
data < 5  # 불리언 데이터프레임

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [86]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### loc와 iloc으로 선택하기

In [87]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [88]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [89]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [90]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [91]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [92]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [93]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 5.2.4 정수 인덱스

In [94]:
ser = pd.Series(np.arange(3.))
ser  # 인덱스가 정수인 경우 라벨/정수 인덱스 혼동 주의

0    0.0
1    1.0
2    2.0
dtype: float64

In [95]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [96]:
ser[:1]

0    0.0
dtype: float64

In [97]:
ser.loc[:1]  # 라벨 인덱스

0    0.0
1    1.0
dtype: float64

In [98]:
ser.iloc[:1]  # 정수 인덱스

0    0.0
dtype: float64

### 5.2.5 산술 연산과 데이터 정렬

In [99]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [100]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [101]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [102]:
s1 + s2  # outer join과 유사, 겹치는 인덱스 없으면 NA

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [103]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [104]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [105]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [106]:
df1 + df2  # 각 데이터프레임의 인덱스와 컬럼이 모두 합쳐짐

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [107]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [108]:
df1

A
0  1
1  2

In [109]:
df2

B
0  3
1  4

In [110]:
df1 - df2  # 겹치는 로우나 컬럼 라벨이 없으면 모두 NA

A   B
0 NaN NaN
1 NaN NaN

#### 산술 연산 메서드에 채워 넣을 값 지정하기

In [111]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan

In [112]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [113]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [114]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [115]:
df1.add(df2, fill_value=0)  # 존재하지 않는 축의 값을 특수한 값(0)으로 지정

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [116]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [117]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [118]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### DataFrame과 Series 간의 연산
브로드캐스팅

In [119]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [120]:
arr[0]

array([0., 1., 2., 3.])

In [121]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [122]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [123]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [124]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [125]:
series2 = pd.Series(range(3),  index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [126]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [127]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [128]:
frame.sub(series3, axis='index')  # 연산을 적용할 축을 로우로 지정(axisi=0과 동일)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.6 함수 적용과 매핑

In [129]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [130]:
np.abs(frame)  # 유니버설 함수 적용

b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [131]:
f = lambda x: x.max() - x.min()
frame.apply(f)  # 각 컬럼이나 로우(1차원 배열)에 함수 적용

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [132]:
frame.apply(f, axis='columns')

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [133]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [134]:
format = lambda x: '%.2f' % x
frame.applymap(format)  # 배열의 각 원소에 함수 적용

b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [135]:
frame['e'].map(format)  # 시리즈의 각 원소에 함수 적용

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

### 5.2.7 정렬과 순위

In [136]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()  # 인덱스 순으로 정렬

a    1
b    2
c    3
d    0
dtype: int64

In [137]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()  # 로우 기준 정렬

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [138]:
frame.sort_index(axis=1)  # 컬럼 기준 정렬

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [139]:
frame.sort_index(axis=1, ascending=False)  # 내림차순 정렬

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [140]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()  # 값을 기준으로 정렬

2   -3
3    2
0    4
1    7
dtype: int64

In [141]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()  # NA 값은 정렬할 때 마지막에 위치

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [142]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [143]:
frame.sort_values(by='b')  # 값 정렬 기준 컬럼 설정

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [144]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [145]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()  # 순위(동률인 데이터는 평균 순위)

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [146]:
obj.rank(method='first')  # 동률인 경우 먼저 등장한 순서대로 순위 적용

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [147]:
# 내림차순 순위, 동률인 경우 그룹 내에서 가장 높은 순위 적용
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [148]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [149]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 5.2.8 중복 인덱스

In [150]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [151]:
obj.index.is_unique

False

In [152]:
obj['a']

a    0
a    1
dtype: int64

In [153]:
obj['c']

4

In [154]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.274992  0.228913  1.352917
a  0.886429 -2.001637 -0.371843
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

In [155]:
df.loc['b']

0         1         2
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

## 5.3 기술 통계 계산과 요약

In [156]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [157]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [158]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [159]:
df.mean(axis='columns', skipna=False)  # NA 값 제외가 default

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [160]:
df.idxmax()  # 최댓값의 인덱스

one    b
two    d
dtype: object

In [161]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [162]:
df.describe()  # 요약 통계량(수치형 데이터)

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [163]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()  # 요약 통계량(범주형 데이터)

count     16
unique     3
top        a
freq       8
dtype: object

### 5.3.1 상관관계와 공분산

In [164]:
import pandas_datareader.data as web

all_data = {ticker: web.get_data_yahoo(ticker) 
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close'] 
                      for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] 
                       for ticker, data in all_data.items()})

In [165]:
returns = price.pct_change()  # 각 주식의 퍼센트 변화율
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-04-01  0.006959 -0.000225  0.027909  0.033413
2021-04-05  0.023577  0.020266  0.027728  0.041071
2021-04-06  0.002462 -0.012580 -0.004858 -0.000359
2021-04-07  0.013390  0.005290  0.008230  0.011206
2021-04-08  0.010868 -0.002001  0.013525  0.005867

In [166]:
returns['MSFT'].corr(returns['IBM'])  # 상관관계

0.5317427162473064

In [167]:
returns['MSFT'].cov(returns['IBM'])  # 공분산

0.00015146321641945157

In [168]:
returns.MSFT.corr(returns.IBM)  # 파이썬 변수명 규칙에 맞는 컬럼 선택

0.5317427162473064

In [169]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.447050  0.712475  0.650457
IBM   0.447050  1.000000  0.531743  0.499260
MSFT  0.712475  0.531743  1.000000  0.778122
GOOG  0.650457  0.499260  0.778122  1.000000

In [170]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000365  0.000140  0.000237  0.000209
IBM   0.000140  0.000268  0.000151  0.000138
MSFT  0.000237  0.000151  0.000302  0.000228
GOOG  0.000209  0.000138  0.000228  0.000283

In [171]:
returns.corrwith(returns.IBM)  # 상관관계 대상 지정

AAPL    0.447050
IBM     1.000000
MSFT    0.531743
GOOG    0.499260
dtype: float64

In [172]:
returns.corrwith(volume)  # 시가총액의 퍼센트 변화율에 대한 상관관계

AAPL   -0.076279
IBM    -0.115012
MSFT   -0.084409
GOOG   -0.133489
dtype: float64

### 5.3.2 유일값, 값 세기, 멤버십

In [173]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [174]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [175]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
a    3
d    1
dtype: int64

In [176]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [177]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [178]:
# 여러 값이 들어 있는 배열에서 유일한 값의 색인 배열 구하기
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [179]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [180]:
# 전체의 유일한 값별로 각 컬럼에서의 출현빈도 구하기
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0